"use client";
import Link from "next/link";
import { useState } from "react";
import { tools } from "@/app/lib/tools/registry";
import { TOOL_CATEGORIES, type ToolCategory } from "@/app/lib/tools/types";
import type { LifeStage } from "@/app/lib/audience";
import { isHighlighted, isProfileEmpty, sortByAudience } from "@/lib/personalize";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { PersonalizationToggle } from "./PersonalizationToggle";
import { usePersonalization } from "./usePersonalization";

const STAGES: {id:string;label:string; stages?:LifeStage[]; universal?:boolean}[]=[{id:"all",label:"すべて"},{id:"pregnancy",label:"妊活・妊娠",stages:["pregnancy"]},{id:"baby",label:"産後・0〜1歳",stages:["newborn","infant"]},{id:"preschool",label:"乳幼児（1〜6歳）",stages:["infant","toddler"]},{id:"school",label:"学童",stages:["schoolAge"]},{id:"work",label:"働く・お金",stages:["adult"]},{id:"care",label:"介護",stages:["senior"]},{id:"universal",label:"暮らし全般",universal:true}];
const UI:Record<ToolCategory,{icon:string;className:string;copy:string}>={pregnancy:{icon:"○",className:"category-pregnancy",copy:"妊娠週数から出産準備まで"},childcare:{icon:"◇",className:"category-childcare",copy:"成長と毎日の育児を支える"},kaji:{icon:"⌂",className:"category-kaji",copy:"料理と家事の迷いを短く"},money:{icon:"¥",className:"category-money",copy:"家計と制度を数字で見通す"},health:{icon:"+",className:"category-health",copy:"からだの目安を穏やかに確認"},career:{icon:"□",className:"category-career",copy:"働き方と手取りを整理する"},care:{icon:"∞",className:"category-care",copy:"介護の費用と段取りを支える"}};
export function PersonalizedToolDirectory(){const [stage,setStage]=useState("all");const {settings,ready}=usePersonalization();const empty=!ready||isProfileEmpty(settings.profile);const selected=STAGES.find((x)=>x.id===stage)!;const categories=Object.keys(TOOL_CATEGORIES) as ToolCategory[];return <><div className="stage-axis mt-5"><p className="font-bold">ライフステージから横断して探す</p><div className="mt-2 flex gap-2 overflow-x-auto pb-2">{STAGES.map((s)=><button key={s.id} type="button" aria-pressed={stage===s.id} className="stage-axis-button" onClick={()=>setStage(s.id)}>{s.label}</button>)}</div></div><div className="mt-4 flex justify-end"><PersonalizationToggle/></div>{categories.map((cat)=>{let list=sortByAudience(tools.filter((t)=>t.category===cat),empty?null:settings.profile);if(stage!=="all")list=list.filter((t)=>selected.universal?t.audience.universal:t.audience.lifeStages.some((x)=>selected.stages?.includes(x)));if(settings.relatedOnly&&!empty)list=list.filter((t)=>isHighlighted(settings.profile,t.audience));if(!list.length)return null;return <section key={cat} className={`category-section ${UI[cat].className}`}><SectionHeading id={cat}><span aria-hidden="true" className="mr-2">{UI[cat].icon}</span>{TOOL_CATEGORIES[cat]}<span className="ml-3 text-sm font-normal text-ink-muted">{UI[cat].copy}</span></SectionHeading><ul className="grid gap-3 sm:grid-cols-2">{list.map((t)=><li key={t.slug}>{t.status==="live"?<Link prefetch={false} href={`/tools/${t.category}/${t.slug}`} className={`tool-card block h-full rounded-card border bg-paper p-5 ${!empty&&isHighlighted(settings.profile,t.audience)?"is-personalized":"border-line"}`}>{!empty&&isHighlighted(settings.profile,t.audience)&&<span className="personalized-label">あなた向け</span>}<span className="font-medium">{t.title}</span><span className="mt-1 block text-sm text-ink-muted">{t.description}</span></Link>:<div className="h-full rounded-card border border-dashed border-line p-4 text-ink-muted"><span className="font-medium">{t.title}</span><span className="mt-1 block text-sm">準備中</span></div>}</li>)}</ul></section>})}</>}
